### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by stork119** [stork119/PathwayPackage#7]
Traceback (most recent call last):
  File "WorkflowEngine.py", line 19, in <module>
    main()
  File "WorkflowEngine.py", line 10, in main
    LC.configure()
  File "/cygdrive/d/KN/PathwayPackage/python/modules/logs_configuration.py", line 9, in configure
    logging.config.fileConfig('logging.conf', defaults={'logfilename': log_filename}, disable_existing_loggers=False) #disable_existing_loggers=True, putting name of every module in logging.conf would be needed, False if we gonna make it unnecesarry
  File "/usr/lib/python2.7/logging/config.py", line 85, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python2.7/logging/config.py", line 163, in _install_handlers
    h = klass(*args)
  File "/usr/lib/python2.7/logging/__init__.py", line 911, in **init**
    StreamHandler.**init**(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 941, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/cygdrive/d/KN/PathwayPackage/python/C:/Users/Agnieszka/Documents/GitHub/PathwayPackage/python/logs/2016_03_18__09_34.log'

**Comment by stork119** [comment]
`$ python3.4 WorkflowEngine.py
Traceback (most recent call last):
  File "WorkflowEngine.py", line 19, in <module>
    main()
  File "WorkflowEngine.py", line 10, in main
    LC.configure()
  File "/cygdrive/d/KN/PathwayPackage/python/modules/logs_configuration.py", line 9, in configure
    logging.config.fileConfig('logging.conf', defaults={'logfilename': log_filename}, disable_existing_loggers=False) #disable_existing_loggers=True, putting name of every module in logging.conf would be needed, False if we gonna make it unnecesarry
  File "/usr/lib/python3.4/logging/config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python3.4/logging/config.py", line 147, in _install_handlers
    h = klass(*args)
  File "/usr/lib/python3.4/logging/__init__.py", line 1006, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.4/logging/__init__.py", line 1030, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
**FileNotFoundError: [Errno 2] No such file or directory: '/cygdrive/d/KN/PathwayPackage/python/C:/Users/Agnieszka/Documents/GitHub/PathwayPackage/python/logs/2016_03_18__11_38.log'**
`

**Comment by stork119** [comment]
@Setnea  spojrz na fragment : 
**/cygdrive/d/KN/PathwayPackage/python/C:/Users/Agnieszka/Documents/GitHub/PathwayPackage/python/logs/2016_03_18__11_38.log**

Nie ma sie co dziwic ze nie ma takiej sciezki.
